### PR TITLE
Add Stanford's Algorithms courses

### PR DESCRIPTION
**Pull request by d4rkr00t**

### CODE REVIEW

**Comment by ericelliott** [comment]
Does this compete directly with the MIT Algorithms course? If not, how is it different or better?

**Comment by d4rkr00t** [comment]
They have much in common but Princeton course also covers:
* Analysis of Algorithms — Observations, Mathematical Models, Order-of-Growth, Theory of Algorithms, Memory
* More about elementary sort algorithms — Selection Sort, Shellsort
* Quick Sort
* Stacks and Queues, Priority Queues
* Elementary Symbol Tables
* 2-3 Search Trees, Red-Black BSTs
* Geometric Applications of BSTs

Full list of topics covered in course:
```
Union-Find
  Dynamic Connectivity
  Quick Find
  Quick Union
  Quick-Union Improvements
  Union-Find Applications

Analysis of Algorithms
  Analysis of Algorithms Introduction
  Observations
  Mathematical Models
  Order-of-Growth Classifications
  Theory of Algorithms
  Memory

Stacks and Queues
  Stacks
  Resizing Arrays
  Queues
  Generics
  Iterators
  Stack and Queue Applications

Elementary Sorts
  Sorting Introduction
  Selection Sort
  Insertion Sort
  Shellsort
  Shuffling
  Convex Hull

Mergesort 
  Mergesort
  Bottom-up Mergesort
  Sorting Complexity
  Comparators
  Stability

Quicksort
  Quicksort
  Selection
  Duplicate Keys
  System Sorts

Priority Queues
  APIs and Elementary Implementations
  Binary Heaps
  Heapsort
  Event-Driven Simulation

Elementary Symbol Tables
  Symbol Table API
  Elementary Implementations
  Ordered Operations
  Binary Search Trees
  Ordered Operations in BSTs
  Deletion in BSTs

Balanced Search Trees
  2-3 Search Trees
  Red-Black BSTs
  B-Trees

Geometric Applications of BSTs
  1d Range Search
  Line Segment Intersection
  Kd-Trees
  Interval Search Trees
  Rectangle Intersection

Hash Functions
  Hash Functions
  Separate Chaining
  Linear Probing
  Hash Table Context
  Symbol Table Applications: Sets
  Symbol Table Applications: Dictionary Clients
  Symbol Table Applications: Indexing Clients
  Symbol Table Applications: Sparse Vectors
```

**Comment by ericelliott** [comment]
Would Princeton's Design and Analysis of Algorithms complement the existing material better than this course?

**Comment by ericelliott** [comment]
Perhaps even better: Stanford's [Design and Analysis of Algorithms 1](https://www.coursera.org/course/algo)  & [2](https://www.coursera.org/course/algo2)? =)

I like that the video lectures are very easy to find on-demand with Stanford's courses.

**Comment by d4rkr00t** [comment]
Yep, Stanford's look better. :)

**Comment by ericelliott** [comment]
Want to update this PR with those links? I'd be happy to merge that. =)

**Comment by d4rkr00t** [comment]
Yes, I'll update it in few minutes.

**Comment by d4rkr00t** [comment]
Should I remove MIT's one?

**Pull request merged**
