### PR TITLE
add udacity media query course link

### PR DESCRIPTION
**Pull request by juliusakula**
Hi again,

This is an extremely high quality (and free) course provided by Udacity and Google. This course has 74 pages which are either videos or quizzes. It teaches creating custom media queries and what responsive design means at a high level, the importance of making content work across any device so as not to lose users when the site fails to be useful or convenient on a mobile device, for example. It doesn't use a framework like bootstrap its the lowest level possible explaination of CSS media queries at a reasonable pace.

#course

### CODE REVIEW

**Comment by juliusakula** [comment]
Udacity also has an awesome free OOP JS course. Teaches prototypical inheritance, psuedo-classical inheritance and more

**Comment by ericelliott** [comment]
Does the OOP course teach compositional techniques & factory functions?

**Comment by juliusakula** [comment]
[the OOP course](https://www.udacity.com/course/object-oriented-javascript--ud015)...

Syllabus description for lesson 4, could be the compositional techniques you mentioned

> There are numerous ways to write concise, maintainable and reusable code in JavaScript and you’ll practice a number of them in this lesson. We’ll start writing a library using basic functions and learn the decorator pattern. Then, we’ll refactor this library into the functional, prototypal and pseudoclassical inheritance models. Finally, we’ll explore sub-classing -- coding objects that directly inherit from objects we’ve previously defined.

Not sure about the factory functions though

**Comment by ericelliott** [comment]
It doesn't look like that course covers either factory functions or any compositional techniques. Instead, it seems to teach pseudoclassical inheritance. I wouldn't recommend it.

**Pull request closed without merging**
